[package]
name = "galnetpedia"
version = "0.1.0"
authors = ["Steve Jabour <steve@jabour.me>"]
edition = "2018"

[dependencies]
console = "0.7.5"
regex = "1.1.6"
indicatif = "0.11.0"
Inflector = "0.11.4"
progressive = "0.1.0"
