version: "3.6"

services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - target: 5984
        published: 5984
    networks:
      - pareco
    volumes:
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data

  elasticsearch:
    container_name: 'pareco.elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    environment:
      cluster.initial_master_nodes: 'pareco.elasticsearch'
      cluster.name: 'pareco'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
      http.cors.allow-headers: 'X-Requested-With,X-Auth-Token,Content-Type,Content-Length'
      http.cors.allow-methods: 'OPTIONS,HEAD,GET,POST,PUT,DELETE'
      http.cors.allow-origin: '*'
      http.cors.enabled: 'true'
      node.name: 'pareco.elasticsearch'
    networks:
      - pareco
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
      - target: 9300
        published: 9300
        protocol: tcp
    volumes:
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.0.0
    environment:
      ELASTICSEARCH_URL: 'http://pareco.elasticsearch:9200'
    networks:
      - pareco
    ports:
      - target: 5601
        published: 5601
        protocol: tcp

  neo4j:
    image: neo4j:3.5.0
    environment:
      NEO4J_AUTH: "${NEO4J_AUTH:-none}"
    ports:
      - target: 7473
        published: 7473
        protocol: tcp
      - target: 7474
        published: 7474
        protocol: tcp
      - target: 7687
        published: 7687
        protocol: tcp
    networks:
      - pareco
    volumes:
      - type: volume
        source: neo4j-data
        target: /data

networks:
  pareco:

volumes:
  couchdb-data:
  elasticsearch-data:
  neo4j-data:
