version: "3.6"

services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    networks:
      - pareco
    volumes:
      - couchdb-data:/opt/couchdb/data

networks:
  pareco:

volumes:
  couchdb-data:
